export enum OrderStatus {
  DRAFT = 'DRAFT',
  OPEN = 'OPEN',
  ACCEPTED = 'ACCEPTED',
  PAID_AND_IN_PRODUCTION = 'PAID_AND_IN_PRODUCTION',
  PRINTING = 'PRINTING',
  QUALITY_CHECK = 'QUALITY_CHECK',
  DISPATCHED = 'DISPATCHED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}
